- name: cloud
  deploys:
    version: "latest"
  config:
    AZURE_LOCATION: "westeurope"
    AZURE_NAME_PREFIX: "validate-azure"
    WEBAPI_NODE_ENV: "production"
- name: onprem
  deploys:
    version: "v0.0.1-latest"
  config:
    AZURE_LOCATION: "centraluseuap"
    AZURE_NAME_PREFIX: "validate-arc-2"
    WEBAPI_NODE_ENV: "production"
    APP_SERVICE_KUBERNETES_ENVIRONMENT_ID: "/subscriptions/f34b22a3-2202-4fb1-b040-1332bd928c84/resourceGroups/logicapps-k8se-04-rg/providers/Microsoft.Web/kubeEnvironments/logicapps-k8se-04-rg-kubeenv"